name: cifar10
num_classes: 10
train_split: 0.85
val_split: 0.15
train_dataset:
  _target_: torchvision.datasets.CIFAR10
  root: ./data
  train: true
  download: true
  transform: 
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.RandomCrop
        size: 32
        padding: 4
        padding_mode: reflect

      - _target_: torchvision.transforms.RandomHorizontalFlip

      - _target_: torchvision.transforms.ToTensor

      # - _target_: torchvision.transforms.Normalize
      #   mean: [0.4914, 0.4822, 0.4465]
      #   std: [0.2470, 0.2435, 0.2616]
      #   inplace: true

test_dataset:
  _target_: torchvision.datasets.CIFAR10
  root: ./data
  train: false
  download: true
  transform: 
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor

      # - _target_: torchvision.transforms.Normalize
      #   mean: [0.4914, 0.4822, 0.4465]
      #   std: [0.2470, 0.2435, 0.2616]
      #   inplace: true

