num_classes: 200
train_split: 0.85
val_split: 0.15
train_dataset:
  _target_: torchvision.datasets.ImageFolder
  root: ./data/tiny-imagenet-200/train
  transform: 
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.RandomResizedCrop
        size: 64
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ToTensor

      # - _target_: torchvision.transforms.Normalize
      #   mean: [0.485, 0.456, 0.406]
      #   std: [0.229, 0.224, 0.225]
      #   inplace: true

test_dataset:
  _target_: torchvision.datasets.ImageFolder
  root: ./data/tiny-imagenet-200/val
  transform: 
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor

      # - _target_: torchvision.transforms.Normalize
      #   mean: [0.485, 0.456, 0.406]
      #   std: [0.229, 0.224, 0.225]
      #   inplace: true