num_classes: 10
name: cifar10
train_split: 0.85
val_split: 0.15
train_dataset:
  _target_: torchvision.datasets.CIFAR10
  root: ./data
  train: true
  download: true
  transform: 
    _target_: torchvision.transforms.ToTensor
  
test_dataset:
  _target_: torchvision.datasets.CIFAR10
  root: ./data
  train: false
  download: true
  transform: 
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor
