defaults:
  - dataset: cifar10

classifier: resnet20 
model:
  _target_: torch.hub.load
  repo_or_dir: chenyaofo/pytorch-cifar-models
  model: cifar10_${classifier}
  pretrained: false

dataloader:  
  train_batch_size: 64
  val_batch_size: 512
  test_batch_size: 512

pl_model:
  _target_: utils.pl_module.ImageClassifier
  clf: ${model}
  num_classes: ${dataset.num_classes}
  optimizer:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 1e-3

trainer:
  log_dir: ./logs/clf/${classifier}/${dataset.name}/
  log_every_n_steps: 10
  accumulate_grad_batches: 1
  gradient_clip_val: 5
  max_epochs: 20
  gpu: 0
  val_monitor: val/acc
  val_check_interval: 1.0
  mode: max
  deterministic: true

hydra:
  run:
    dir: .
  job:
    chdir: false
  output_subdir: null  # prevent auto-creating .hydra in a run dir